apiVersion: apps/v1
kind: Deployment
metadata:
  name: cproduct-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cproduct-service
  template:
    metadata:
      labels:
        app: cproduct-service
    spec:
      containers:
        - name: cproduct-service
          image: mrkendono/product:latest
          ports:
            - containerPort: 5002
          env:
            - name: DB_HOST
              value: user-db
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: MYSQL_PASSWORD
            - name: DB_NAME
              value: user
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

